### ISSUE TITLE
use webpack as the default asset pipeline?

### ISSUE THREAD

**Issue by keathley** [carbonfive/raygun-rails#59]
The standard progression for most complex applications is to move much of logic into React or another front end framework and treat Rails simply as the api. In each of these applications decisions are made after the fact to include a build tool like webpack that can take advantage of the latest features in the javascript world. It can be hard to drop in these tools once you've already started down one path and each implementation looks slightly different then the next.

I propose that we help facilitate those decisions by using webpack as the default asset compilation tool and by establishing a better structure for assets then the standard Rails implementation.  This would also allow developers to take advantage of npm packages, common.js modules, asset compilation with babel, etc. I believe that establishing these conventions will help promote best practices as well as create a more future proof foundation for people creating rails applications.

If this is something that people are interested in doing then I have no issue making the changes and submitting a PR.

What are everyones thoughts?

**Comment by tokafish** [comment]
:+1: on moving away from the asset pipeline. I haven't used webpack specifically, so I can't speak for it over other options.

**Comment by Mrjaco12** [comment]
:+1:  Making folks consider the separate frontend app path at the beginning stages of development is a nice side effect. And having access to those nice JS tools seems like a plus at any stage.

**Comment by shamus** [comment]
:+1: on moving away from the asset pipeline as well -- it doesn't seem to
be moving in the same direction as the rest of the front end stack. But,
the other side of that fence is I don't want the apps generated by
raygun-rails to be at odds with whatever opinions Rails has moving forward.

Back in the spring I thought I saw some projects which were attempting to
make sprockets play nicely with things like SystemJS.

Speaking of SystemJS, I know the community seems more partial to webpack
because React but I was always a bit wary of webpack because React -- we're
talking about polyfilling browser technologies and React isn't one of them
(just like Object.observe turned out not to be all that universal either).

I'd like to see whatever module loader (and transpiler) we work with to be
in line with developments going on with those ECMAScript folks.

But like I said, the last time I surveyed this landscape was in the spring.
That was **ages** ago.

What is the state of affairs now?

**Comment by shamus** [comment]
:+1: on moving away from the asset pipeline as well -- it doesn't seem to be moving in the same direction as the rest of the front end stack. But, the other side of that fence is I don't want the apps generated by raygun-rails to be at odds with whatever opinions Rails has moving forward..

Back in the spring I thought I saw some projects which were attempting to make sprockets play nicely with things like SystemJS.

Speaking of SystemJS, I know the community seems more partial to webpack because React but I was always a bit wary of webpack because React -- we're talking about polyfilling browser technologies and React isn't one of them (just like Object.observe turned out not to be all that universal either).

I'd like to see whatever module loader (and transpiler) we work with to be in line with developments going on with those ECMAScript folks.

But like I said, the last time I surveyed this landscape was in the spring. That was **ages** ago.

**Comment by drtoast** [comment]
:+1: on using webpack for assets by default. We just added it to my project and I wish it had been there from the start. I agree with @shamus that there's a risk in moving away from the standard opinions of the Rails community, but the status quo isn't cutting it for rapidly growing API-driven applications.

**Comment by andrewhao** [comment]
This is probably obvious, but we'd need to document somewhere the gotchas of using Webpack (maybe in the generated README) for those folks who are external to C5. We also need to bake in the defaults with production-ready configs for CI, frontend tests, and Heroku deployment.

**Comment by bomatson** [comment]
a. I love this
b. Why make it the default, as opposed to optional? 

also, "establishing a better structure for assets then the standard Rails implementation" sounds like quite an undertaking + tough to maintain. my 2c

**Comment by keathley** [comment]
@shamus I'm also in favor of trying not to fight rails more then is necessary. I'm happy to do a survey of the other technologies to see if there is a better fit then webpack. I tend to lean towards webpack because 1) I'm familiar with it 2) I think that it provides a lot of functionality that other modules loaders are missing (chunking common files, automatically splitting vendor files, etc.) and 3) I think that it opens the doors to take advantage of other technologies like css modules. That said its definitely not the only choice out there. I'll try to take stock of the other solutions and post some pros and cons here.

@andrewhao I totally agree with you. We'll have to make sure that everything works with our existing tool configuration out of the box. Hopefully establishing these conventions means less work for people going forward.

@bomatson There are a few reasons that I'd like to make this the default. 1) My (anecdotal) experience is that most applications need these tools at some point anyway. Typically the reason that we don't add them is simply time cost. 2) I strongly believe that this is the best tool set for the future.

As for your second point: I really just mean have some better tools from the beginning. This would allow each project to drop in their framework of choice and establish the directory structure that they want. For instance, I'm a fan of grouping together React components with their css and tests in the same directory. Thats pretty trivial in webpack. Not that you couldn't establish that same hierarchy in Rails. It just isn't encouraged.

I don't think that we need to/should be that prescriptive. However, this would create that flexibility.

**Comment by rudyjahchan** [comment]
All for this (surprising no one). To @shamus' point, we should be clear if raygun-rails is best "Rails" practice, or our best practice. I believe it is the latter, but good to tell people why.

Another thing to keep in mind as we build it out is to make it easy to deal with different environments. A lot of the webpack examples don't tackle minifying and caching of their assets, and this is quite frankly wonderful automated in the Rails asset pipeline.

**Comment by keathley** [comment]
@rudyjahchan I tend to agree with you that raygun should be reflective of OUR best practices. If these changes are useful then I think the case could be made to submit some changes to rails proper.

The easiest way to get around cache headers and other problems is to drop everything into the asset pipeline and require it with a manifest file. This is somewhat annoying, however, it does allow the freedom to revert back to the standard asset pipeline if people want to do that. I'm open to alternative (potentially more heavy handed) solutions.

Since this seems like something that people are interested in I'll start spiking out a generic solution so that we can discuss the merits of real code.

**Comment by christiannelson** [comment]
This is a good thread, thanks for starting it and for participating. This is exactly one of the reasons I created Raygun... to be a place where we discuss these sort of important and interesting topics.  :)

Raygun is intended to generate an app with C5 best practices baked in. It also should include things that apply to a vast majority of projects (like 90%+), so that we don't have to spend a lot of time removing things we don't want when we use it. That defeats the point of being able to spin up a new project quickly. :)

So, the first question on my mind is: do a vast majority of Carbon Five projects drop the asset pipeline and use webpack (or something else) instead?

Next question is, does it make sense to drop the asset pipeline for apps that are not an API + JavaScript App (an "old fashioned" app)? That is, is the PR suggesting that C5 _defaults_ to building APIs and JS apps that consume them?

IMHO, the asset pipeline provides a lot of niceties. If we were to drop it in favor of something else, the _something else_ should support these things out of the box (or via configuration in raygun):

- Automatic recompilation when something changes (in development)
- Cache busting asset URIs (e.g. application-<DIGEST>.js) (on in all environments)
-  Asset aggregation (off in development, on elsewhere)
- Asset compression (off in development, on elsewhere)
- CDN Support via `config.action_controller.asset_host` or equivalent
- [Subresource Integrity Checks](https://github.com/rails/sprockets-rails#sri-support) (maybe a nice to have)

Basically, for me, when I spin up a Rails app I want to make sure the things that I'm used to working still work in a comparable fashion.

Is it possible to completely remove the asset pipeline? If we can't, it feels a little icky -- and potentially confusing -- to have both in place in an app at the same time. My guess is that Rails 5 will support this, given the [support for API only apps](http://edgeguides.rubyonrails.org/api_app.html).

And I wonder if there's still a place in the world for apps that use the asset pipeline. My gut feeling is yes, but I could be convinced.

Note that Raygun doesn't support things being optional, mostly because it gets super complicated and creates a lot more around maintenance (because permutations and managing diffs). Though, we could support 2 branches reasonably easily: "old fashioned" and api + spa / webpack. Making more things optional increases complexity beyond the reaped benefit, IMHO.

**Comment by christiannelson** [comment]
@keathley I missed your comment about writing some code to illustrate what this could look like... I think that's an **awesome** idea, BTW.

**Comment by christiannelson** [comment]
A timely post in today's ruby weekly: https://github.com/shakacode/react_on_rails

**Comment by keathley** [comment]
Hey all. I'm going to close this for now. Obviously I haven't spent much/any time on it. Honestly I'm just not that interested in getting this working for Rails. While I think that webpack (or some other node based build tool) is the right way to go for Raygun, Phoenix already supports all of these features out of the box. I'd rather continue focusing my efforts on the Elixir community. 

Thanks for all of the feedback!
